### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by kisstamas1985** [fiverecords/SuperTimecodeConverter#1]
Hello!
I tried to compile on osx 15.7.3 as described, but the final build fails. Previous commands ran without errors.

`cmake --build build
[  4%] Generating SuperTimecodeConverter_artefacts/JuceLibraryCode/SuperTimecodeConverter/PkgInfo
[  9%] Generating SuperTimecodeConverter_artefacts/JuceLibraryCode/JuceHeader.h
[ 13%] Building CXX object CMakeFiles/SuperTimecodeConverter.dir/Main.cpp.o
[ 18%] Building CXX object CMakeFiles/SuperTimecodeConverter.dir/MainComponent.cpp.o
/Users/kisstamas/TCIZE/SuperTimecodeConverter/MainComponent.cpp:133:37: error: reference to 'InputSource' is ambiguous
  133 |         if (eng.getActiveInput() == InputSource::MTC) { inputConfigExpanded = !inputConfigExpanded; updateDeviceSelectorVisibility(); }
      |                                     ^
/Users/kisstamas/TCIZE/SuperTimecodeConverter/MainComponent.cpp:7:7: note: candidate found by name lookup is 'InputSource'
    7 | using InputSource = TimecodeEngine::InputSource;
      |       ^
/Users/kisstamas/TCIZE/JUCE/modules/juce_core/streams/juce_InputSource.h:49:17: note: candidate found by name lookup is 'juce::InputSource'
   49 | class JUCE_API  InputSource
      |                 ^
/Users/kisstamas/TCIZE/SuperTimecodeConverter/MainComponent.cpp:134:63: error: reference to 'InputSource' is ambiguous
  134 |         else { inputConfigExpanded = true; eng.setInputSource(InputSource::MTC); startCurrentMtcInput(); updateInputButtonStates(); updateDeviceSelectorVisibility(); saveSettings(); }
      |                                                               ^
/Users/kisstamas/TCIZE/SuperTimecodeConverter/MainComponent.cpp:7:7: note: candidate found by name lookup is 'InputSource'
    7 | using InputSource = TimecodeEngine::InputSource;
      |       ^
/Users/kisstamas/TCIZE/JUCE/modules/juce_core/streams/juce_InputSource.h:49:17: note: candidate found by name lookup is 'juce::InputSource'
   49 | class JUCE_API  InputSource
      |                 ^
/Users/kisstamas/TCIZE/SuperTimecodeConverter/MainComponent.cpp:139:37: error: reference to 'InputSource' is ambiguous
  139 |         if (eng.getActiveInput() == InputSource::ArtNet) { inputConfigExpanded = !inputConfigExpanded; updateDeviceSelectorVisibility(); }
      |                                     ^
/Users/kisstamas/TCIZE/SuperTimecodeConverter/MainComponent.cpp:7:7: note: candidate found by name lookup is 'InputSource'
    7 | using InputSource = TimecodeEngine::InputSource;
      |       ^
/Users/kisstamas/TCIZE/JUCE/modules/juce_core/streams/juce_InputSource.h:49:17: note: candidate found by name lookup is 'juce::InputSource'
   49 | class JUCE_API  InputSource
      |                 ^
/Users/kisstamas/TCIZE/SuperTimecodeConverter/MainComponent.cpp:140:63: error: reference to 'InputSource' is ambiguous
  140 |         else { inputConfigExpanded = true; eng.setInputSource(InputSource::ArtNet); startCurrentArtnetInput(); updateInputButtonStates(); updateDeviceSelectorVisibility(); saveSettings(); }
      |                                                               ^
/Users/kisstamas/TCIZE/SuperTimecodeConverter/MainComponent.cpp:7:7: note: candidate found by name lookup is 'InputSource'
    7 | using InputSource = TimecodeEngine::InputSource;
      |       ^
/Users/kisstamas/TCIZE/JUCE/modules/juce_core/streams/juce_InputSource.h:49:17: note: candidate found by name lookup is 'juce::InputSource'
   49 | class JUCE_API  InputSource
      |                 ^
/Users/kisstamas/TCIZE/SuperTimecodeConverter/MainComponent.cpp:145:37: error: reference to 'InputSource' is ambiguous
  145 |         if (eng.getActiveInput() == InputSource::SystemTime) { inputConfigExpanded = !inputConfigExpanded; updateDeviceSelectorVisibility(); }
      |                                     ^
/Users/kisstamas/TCIZE/SuperTimecodeConverter/MainComponent.cpp:7:7: note: candidate found by name lookup is 'InputSource'
    7 | using InputSource = TimecodeEngine::InputSource;
      |       ^
/Users/kisstamas/TCIZE/JUCE/modules/juce_core/streams/juce_InputSource.h:49:17: note: candidate found by name lookup is 'juce::InputSource'
   49 | class JUCE_API  InputSource
      |                 ^
/Users/kisstamas/TCIZE/SuperTimecodeConverter/MainComponent.cpp:146:63: error: reference to 'InputSource' is ambiguous
  146 |         else { inputConfigExpanded = true; eng.setInputSource(InputSource::SystemTime); updateInputButtonStates(); updateDeviceSelectorVisibility(); saveSettings(); }
      |                                                               ^
/Users/kisstamas/TCIZE/SuperTimecodeConverter/MainComponent.cpp:7:7: note: candidate found by name lookup is 'InputSource'
    7 | using InputSource = TimecodeEngine::InputSource;
      |       ^
/Users/kisstamas/TCIZE/JUCE/modules/juce_core/streams/juce_InputSource.h:49:17: note: candidate found by name lookup is 'juce::InputSource'
   49 | class JUCE_API  InputSource
      |                 ^
/Users/kisstamas/TCIZE/SuperTimecodeConverter/MainComponent.cpp:151:37: error: reference to 'InputSource' is ambiguous
  151 |         if (eng.getActiveInput() == InputSource::LTC) { inputConfigExpanded = !inputConfigExpanded; updateDeviceSelectorVisibility(); }
      |                                     ^
/Users/kisstamas/TCIZE/SuperTimecodeConverter/MainComponent.cpp:7:7: note: candidate found by name lookup is 'InputSource'
    7 | using InputSource = TimecodeEngine::InputSource;
      |       ^
/Users/kisstamas/TCIZE/JUCE/modules/juce_core/streams/juce_InputSource.h:49:17: note: candidate found by name lookup is 'juce::InputSource'
   49 | class JUCE_API  InputSource
      |                 ^
/Users/kisstamas/TCIZE/SuperTimecodeConverter/MainComponent.cpp:152:63: error: reference to 'InputSource' is ambiguous
  152 |         else { inputConfigExpanded = true; eng.setInputSource(InputSource::LTC); if (!scannedAudioInputs.isEmpty()) startCurrentLtcInput(); updateInputButtonStates(); updateDeviceSelectorVisibility(); saveSettings(); }
      |                                                               ^
/Users/kisstamas/TCIZE/SuperTimecodeConverter/MainComponent.cpp:7:7: note: candidate found by name lookup is 'InputSource'
    7 | using InputSource = TimecodeEngine::InputSource;
      |       ^
/Users/kisstamas/TCIZE/JUCE/modules/juce_core/streams/juce_InputSource.h:49:17: note: candidate found by name lookup is 'juce::InputSource'
   49 | class JUCE_API  InputSource
      |                 ^
/Users/kisstamas/TCIZE/SuperTimecodeConverter/MainComponent.cpp:158:37: error: reference to 'InputSource' is ambiguous
  158 |         if (eng.getActiveInput() == InputSource::ProDJLink) { inputConfigExpanded = !inputConfigExpanded; updateDeviceSelectorVisibility(); }
      |                                     ^
/Users/kisstamas/TCIZE/SuperTimecodeConverter/MainComponent.cpp:7:7: note: candidate found by name lookup is 'InputSource'
    7 | using InputSource = TimecodeEngine::InputSource;
      |       ^
/Users/kisstamas/TCIZE/JUCE/modules/juce_core/streams/juce_InputSource.h:49:17: note: candidate found by name lookup is 'juce::InputSource'
   49 | class JUCE_API  InputSource
      |                 ^
/Users/kisstamas/TCIZE/SuperTimecodeConverter/MainComponent.cpp:159:63: error: reference to 'InputSource' is ambiguous
  159 |         else { inputConfigExpanded = true; eng.setInputSource(InputSource::ProDJLink); startCurrentProDJLinkInput(); updateInputButtonStates(); updateDeviceSelectorVisibility(); saveSettings(); }
      |                                                               ^
/Users/kisstamas/TCIZE/SuperTimecodeConverter/MainComponent.cpp:7:7: note: candidate found by name lookup is 'InputSource'
    7 | using InputSource = TimecodeEngine::InputSource;
      |       ^
/Users/kisstamas/TCIZE/JUCE/modules/juce_core/streams/juce_InputSource.h:49:17: note: candidate found by name lookup is 'juce::InputSource'
   49 | class JUCE_API  InputSource
      |                 ^
/Users/kisstamas/TCIZE/SuperTimecodeConverter/MainComponent.cpp:165:37: error: reference to 'InputSource' is ambiguous
  165 |         if (eng.getActiveInput() == InputSource::StageLinQ) { inputConfigExpanded = !inputConfigExpanded; updateDeviceSelectorVisibility(); }
      |                                     ^
/Users/kisstamas/TCIZE/SuperTimecodeConverter/MainComponent.cpp:7:7: note: candidate found by name lookup is 'InputSource'
    7 | using InputSource = TimecodeEngine::InputSource;
      |       ^
/Users/kisstamas/TCIZE/JUCE/modules/juce_core/streams/juce_InputSource.h:49:17: note: candidate found by name lookup is 'juce::InputSource'
   49 | class JUCE_API  InputSource
      |                 ^
/Users/kisstamas/TCIZE/SuperTimecodeConverter/MainComponent.cpp:166:63: error: reference to 'InputSource' is ambiguous
  166 |         else { inputConfigExpanded = true; eng.setInputSource(InputSource::StageLinQ); startCurrentStageLinQInput(); updateInputButtonStates(); updateDeviceSelectorVisibility(); saveSettings(); }
      |                                                               ^
/Users/kisstamas/TCIZE/SuperTimecodeConverter/MainComponent.cpp:7:7: note: candidate found by name lookup is 'InputSource'
    7 | using InputSource = TimecodeEngine::InputSource;
      |       ^
/Users/kisstamas/TCIZE/JUCE/modules/juce_core/streams/juce_InputSource.h:49:17: note: candidate found by name lookup is 'juce::InputSource'
   49 | class JUCE_API  InputSource
      |                 ^
/Users/kisstamas/TCIZE/SuperTimecodeConverter/MainComponent.cpp:231:37: error: reference to 'InputSource' is ambiguous
  231 |         if (eng.getActiveInput() == InputSource::LTC) eng.setUserOverrodeLtcFps(true);
      |                                     ^
/Users/kisstamas/TCIZE/SuperTimecodeConverter/MainComponent.cpp:7:7: note: candidate found by name lookup is 'InputSource'
    7 | using InputSource = TimecodeEngine::InputSource;
      |       ^
/Users/kisstamas/TCIZE/JUCE/modules/juce_core/streams/juce_InputSource.h:49:17: note: candidate found by name lookup is 'juce::InputSource'
   49 | class JUCE_API  InputSource
      |                 ^
/Users/kisstamas/TCIZE/SuperTimecodeConverter/MainComponent.cpp:247:37: error: reference to 'InputSource' is ambiguous
  247 |         if (eng.getActiveInput() == InputSource::LTC) eng.setUserOverrodeLtcFps(true);
      |                                     ^
/Users/kisstamas/TCIZE/SuperTimecodeConverter/MainComponent.cpp:7:7: note: candidate found by name lookup is 'InputSource'
    7 | using InputSource = TimecodeEngine::InputSource;
      |       ^
/Users/kisstamas/TCIZE/JUCE/modules/juce_core/streams/juce_InputSource.h:49:17: note: candidate found by name lookup is 'juce::InputSource'
   49 | class JUCE_API  InputSource
      |                 ^
/Users/kisstamas/TCIZE/SuperTimecodeConverter/MainComponent.cpp:304:49: error: reference to 'InputSource' is ambiguous
  304 |         if (currentEngine().getActiveInput() == InputSource::LTC)
      |                                                 ^
/Users/kisstamas/TCIZE/SuperTimecodeConverter/MainComponent.cpp:7:7: note: candidate found by name lookup is 'InputSource'
    7 | using InputSource = TimecodeEngine::InputSource;
      |       ^
/Users/kisstamas/TCIZE/JUCE/modules/juce_core/streams/juce_InputSource.h:49:17: note: candidate found by name lookup is 'juce::InputSource'
   49 | class JUCE_API  InputSource
      |                 ^
/Users/kisstamas/TCIZE/SuperTimecodeConverter/MainComponent.cpp:323:61: error: reference to 'InputSource' is ambiguous
  323 |         if (sel >= 0 && currentEngine().getActiveInput() == InputSource::MTC)
      |                                                             ^
/Users/kisstamas/TCIZE/SuperTimecodeConverter/MainComponent.cpp:7:7: note: candidate found by name lookup is 'InputSource'
    7 | using InputSource = TimecodeEngine::InputSource;
      |       ^
/Users/kisstamas/TCIZE/JUCE/modules/juce_core/streams/juce_InputSource.h:49:17: note: candidate found by name lookup is 'juce::InputSource'
   49 | class JUCE_API  InputSource
      |                 ^
/Users/kisstamas/TCIZE/SuperTimecodeConverter/MainComponent.cpp:338:49: error: reference to 'InputSource' is ambiguous
  338 |         if (currentEngine().getActiveInput() == InputSource::ArtNet)
      |                                                 ^
/Users/kisstamas/TCIZE/SuperTimecodeConverter/MainComponent.cpp:7:7: note: candidate found by name lookup is 'InputSource'
    7 | using InputSource = TimecodeEngine::InputSource;
      |       ^
/Users/kisstamas/TCIZE/JUCE/modules/juce_core/streams/juce_InputSource.h:49:17: note: candidate found by name lookup is 'juce::InputSource'
   49 | class JUCE_API  InputSource
      |                 ^
/Users/kisstamas/TCIZE/SuperTimecodeConverter/MainComponent.cpp:357:49: error: reference to 'InputSource' is ambiguous
  357 |         if (currentEngine().getActiveInput() == InputSource::ProDJLink)
      |                                                 ^
/Users/kisstamas/TCIZE/SuperTimecodeConverter/MainComponent.cpp:7:7: note: candidate found by name lookup is 'InputSource'
    7 | using InputSource = TimecodeEngine::InputSource;
      |       ^
/Users/kisstamas/TCIZE/JUCE/modules/juce_core/streams/juce_InputSource.h:49:17: note: candidate found by name lookup is 'juce::InputSource'
   49 | class JUCE_API  InputSource
      |                 ^
/Users/kisstamas/TCIZE/SuperTimecodeConverter/MainComponent.cpp:362:54: error: reference to 'InputSource' is ambiguous
  362 |         else if (currentEngine().getActiveInput() == InputSource::StageLinQ)
      |                                                      ^
/Users/kisstamas/TCIZE/SuperTimecodeConverter/MainComponent.cpp:7:7: note: candidate found by name lookup is 'InputSource'
    7 | using InputSource = TimecodeEngine::InputSource;
      |       ^
/Users/kisstamas/TCIZE/JUCE/modules/juce_core/streams/juce_InputSource.h:49:17: note: candidate found by name lookup is 'juce::InputSource'
   49 | class JUCE_API  InputSource
      |                 ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [CMakeFiles/SuperTimecodeConverter.dir/MainComponent.cpp.o] Error 1
make[1]: *** [CMakeFiles/SuperTimecodeConverter.dir/all] Error 2
make: *** [all] Error 2`

**Comment by fiverecords** [comment]
Thanks for reporting this! It's a name collision between our InputSource alias and juce::InputSource from juce_core/streams/juce_InputSource.h. When building with CMake, JuceHeader.h pulls in using namespace juce; which makes both visible at the same scope. Projucer builds don't hit this because they handle the namespace differently.
Already fixed in the development branch (renamed the alias to avoid the collision). It'll be included in the next release.
For now, please grab the pre-built binary from the [Releases](https://github.com/fiverecords/SuperTimecodeConverter/releases) page.

**Comment by kisstamas1985** [comment]
thank you! the pre-built works fine!
